### ISSUE TITLE
R computation different for Wilcoxon between difference_test() and ttest()

### ISSUE THREAD

**Issue by Jean-Diddy** [researchpy/researchpy#10]
Hello, 

It may be naive (and sorry for that) but I don't understand why the computation or r correlation coefficient is different for Wilcoxon test wether we use difference_test() and ttest() function. For ttest() the Rosenthal r is computed and for the difference_test() the Point biserial correlation r is computed.

Also to improve the package I would like to suggest to add the median for these non-parametric tests and homogenize the output of these two functions (with one function for wilcoxon we get the z but not the w and other parameters). 

Yet, maybe there is a purpose to do so that I don't understand, could you explain please ?

Thank you for this package and your help :)

**Comment by Corey-Bryant** [comment]
Hello Jean-Diddy,

Regarding the difference between difference_test() and ttest(), there is no methodological reasoning for that.  The reason why that was decided, at the time, was to preserve the known functionality of ttest(). I had thought about adding the ability for one to choose the type of R coefficient returned but decided to go the route I did. I can add this functionality in the next update.

Both of the functions return the W-statistic for the Wilcoxon signed-rank test, but only the ttest() calculation returns the Z-statistic. I do agree that they should be homogenized and will work on that for the next release.

Thank you for your use, questions, and suggestions!


Best,

Corey
