### ISSUE TITLE
FutureWarning with pandas series.append() in ttest.py

### ISSUE THREAD

**Issue by jm-boley** [researchpy/researchpy#14]
I'll keep this brief since both the problem and reproduction of it are simple and obvious. Running the ttest function generates the message
```
researchpy/ttest.py:38: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
```
in the output, in addition to the desired output. I've checked the source code here and I can see that the offending line is still present.

If desired I could pull and fix the problem myself, as well as hunt down any other "legacy" code.

**Comment by Corey-Bryant** [comment]
Hey jm-boley,

Thanks for flagging this, issue has been addressed.


Best,

Corey

**Comment by simplg** [comment]
Hi @Corey-Bryant ,

Do you have any planned release schedule with this changes? Pandas new versions seem to have deprecated and removed Series.append and makes it impossible to use this library for ttest (and I suppose other methods using Series.append).

Pandas version: 2.0.0
Researchpy version: 0.3.5

Thanks for everything.
